// src/lib/Vue Examples/dialog.vue
<template>
  <div class="fixed inset-0 flex items-center justify-center">
    <button type="button" @click="openModal" class="rounded-md bg-black bg-opacity-20 px-4 py-2 text-sm font-medium text-white hover:bg-opacity-30 focus:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75">Open dialog</button>
  </div>
  <TransitionRoot appear :show="isOpen" as="template">
    <Dialog as="div" @close="closeModal" class="relative z-10">
      <TransitionChild as="template" enter="duration-300 ease-out" enter-from="opacity-0" enter-to="opacity-100" leave="duration-200 ease-in" leave-from="opacity-100" leave-to="opacity-0">
        <div class="fixed inset-0 bg-black bg-opacity-25" />
      </TransitionChild>

      <div class="fixed inset-0 overflow-y-auto">
        <div class="flex min-h-full items-center justify-center p-4 text-center">
          <TransitionChild as="template" enter="duration-300 ease-out" enter-from="opacity-0 scale-95" enter-to="opacity-100 scale-100" leave="duration-200 ease-in" leave-from="opacity-100 scale-100" leave-to="opacity-0 scale-95">
            <DialogPanel class="w-full max-w-md transform overflow-hidden rounded-2xl bg-white p-6 text-left align-middle shadow-xl transition-all">
              <DialogTitle as="h3" class="text-lg font-medium leading-6 text-gray-900"> Payment successful </DialogTitle>
              <div class="mt-2">
                <p class="text-sm text-gray-500">Your payment has been successfully submitted. We’ve sent you an email with all of the details of your order.</p>
              </div>

              <div class="mt-4">
                <button type="button" class="inline-flex justify-center rounded-md border border-transparent bg-blue-100 px-4 py-2 text-sm font-medium text-blue-900 hover:bg-blue-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2" @click="closeModal">Got it, thanks!</button>
              </div>
            </DialogPanel>
          </TransitionChild>
        </div>
      </div>
    </Dialog>
  </TransitionRoot>
</template>

<script setup>
import { ref } from "vue";
import { TransitionRoot, TransitionChild, Dialog, DialogPanel, DialogTitle } from "@headlessui/vue";

const isOpen = ref(true);

function closeModal() {
  isOpen.value = false;
}
function openModal() {
  isOpen.value = true;
}
</script>

// src/lib/Dialog.svelte
<script>
  import { Dialog, DialogOverlay, DialogTitle, DialogDescription } from "@rgossiaux/svelte-headlessui";
  import { fade, scale, slide } from "svelte/transition";
  import { createEventDispatcher } from "svelte";

  export let isOpen = true;
  export let modalClass = "mx-10";
  export let modalStyle = "";
  let isFullyOpen = true;
  const dispatch = createEventDispatcher();

  function onClose() {
    isOpen = false;
    dispatch("close");
  }
</script>

<!--  sm:modal-middle -->
<Dialog class="inset-0 fixed modal modal-bottom modal-open" open={isFullyOpen} on:close={onClose} static>
  <div
    transition:fade={{
      duration: 300,
    }}
    class="inset-0 absolute"
  >
    <DialogOverlay class="absolute inset-0 bg-black opacity-70" />
  </div>
  <!--     transition:scale={{
      delay: 0,
      duration: 200,
      start: 0.7,
    }} -->
  <div
    class={"modal-box max-w-2xl " + modalClass}
    style={modalStyle}
    transition:slide={{
      duration: 300,
    }}
    on:introstart={() => (isFullyOpen = true)}
    on:outroend={() => (isFullyOpen = false)}
  >
    <slot>
      <DialogTitle as="h3" class="font-bold text-lg">Dialog w/o content</DialogTitle>
      <DialogDescription class="py-">Please add some content</DialogDescription>
      <button for="" class="btn btn-sm btn-circle absolute right-2 top-2" on:click={onClose}>✕</button>
      <div class="modal-action">
        <button type="button" on:click={onClose} class="btn">Got it, thanks!</button>
      </div>
    </slot>
  </div>
</Dialog>

<!-- <Transition show={isOpen}>
  <Dialog open={isOpen} on:close={() => (isOpen = false)} class="relative z-10">
    <TransitionChild enter="ease-out duration-300" enterFrom="opacity-0" enterTo="opacity-100" leave="ease-in duration-200" leaveFrom="opacity-100" leaveTo="opacity-0">
      <DialogOverlay />
    </TransitionChild>

    <div class="fixed inset-0 overflow-y-auto">
      <div class="flex min-h-full items-center justify-center p-4 text-center">
        <TransitionChild enter="ease-out duration-300" enterFrom="opacity-0 scale-95" enterTo="opacity-100 scale-100" leave="ease-in duration-200" leaveFrom="opacity-100 scale-100" leaveTo="opacity-0 scale-95">
          <div class="w-full max-w-md transform overflow-hidden rounded-2xl bg-white p-6 text-left align-middle shadow-xl transition-all">
            <DialogTitle as="h3" class="text-lg font-medium leading-6 text-gray-900">Payment successful</DialogTitle>

            <DialogDescription class="mt-2 text-sm text-gray-500">This will permanently deactivate your account</DialogDescription>

            <div class="mt-4">
              <button type="button" on:click={() => (isOpen = false)} class="inline-flex justify-center rounded-md border border-transparent bg-blue-100 px-4 py-2 text-sm font-medium text-blue-900 hover:bg-blue-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2">Got it, thanks!</button>
            </div>
          </div>
        </TransitionChild>
      </div>
    </div>
  </Dialog>
</Transition> -->
